### ISSUE TITLE
Styled blows up at build

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#399]
Not sure why.

```
// @flow strict-local

// flowlint-next-line untyped-import:off
// eslint-disable-next-line @atlassian/tangerine/import/default-import-names
import styledComponent from 'styled-components';
import { styled } from '@compiled/react';
import { colors, typography } from '@atlaskit/theme';
import { gridSize } from '@atlassian/jira-common-legacy-do-not-add-anything-new/src/styles';

/**
 * The amount content item borders 'flow' into the left gutter area.
 */
const gutterLeftRightPullback = gridSize / 2;

/**
 * The small font size defined here: https://atlassian.design/guidelines/product/foundations/typography
 */
const fontSizeSmall = '11px';

export const StyledContainer = styledComponent.div`
    display: flex;
    height: ${gridSize * 21}px;
    width: ${gridSize * 30}px;
    padding-top: ${gridSize * 2}px;
    flex-direction: column;
    color: inherit;
    background: ${(props) => props.bgColor || 'white'};
    :not(:first-of-type) {
        margin-left: ${gridSize * 1.5}px;
    }
    border: none;
    border-radius: 3px;
    border-left: ${gridSize * 2.5}px solid ${(props) => props.barColor || colors.N20};
    box-sizing: border-box;
    box-shadow: 0 1px 1px ${colors.N50A}, 0 0 1px ${colors.N60A};
    transition: box-shadow 0.3s ease-in-out, border-color 0.6s ease-in;
    :hover {
        box-shadow: 0 2px 4px ${colors.N50A}, 0 0 1px ${colors.N60A};
        cursor: pointer;
    }
`;

export const Header = styledComponent.div`
    text-align: left;
    color: inherit;
    width: 100%;
    /* Total margin needed is 28px. We reserve 14px to the subheading for line height.
    */
    margin-bottom: ${gridSize * 1.5}px;
    /* Pull the header back one grid space, as it must partly overlap with the left border bar */
    margin-left: -${gridSize + gutterLeftRightPullback}px;
    display: flex;
    align-items: start;
`;

export const Heading = styledComponent.div`
    display: inline-block;
    vertical-align: top;
    flex: 1;
    margin-left: ${gridSize}px;
    margin-right: ${gutterLeftRightPullback}px;
    overflow: hidden;
`;

export const ContentRow = styledComponent.div`
    display: flex;
    padding-left: ${gridSize * 2.75}px;
    padding-right: ${gridSize * 1.5}px;
    margin-bottom: ${gridSize / 4}px;
`;

export const TryLozengeContainer = styledComponent.div`
    padding-top: ${gridSize * 2.3}px;
`;

export const SetupProjectNameHeading = styledComponent.p`
    ${typography.h400};
    color: ${colors.N800};
    font-weight: 600;
    line-height: 1.2;
    margin: 0;
    white-space: initial;
    max-width: ${gridSize * 16}px;
`;

export const SetupProjectContainer = styledComponent.div`
    flex: 1;
    display: flex;
    align-items: start;
`;

export const BoardContentRow = styledComponent(ContentRow)`
    border-top: 1px solid #dcd9f8;
    margin: 0;
    height: ${gridSize * 3.5}px;
    align-items: center;
    padding-right: ${gridSize * 1.5}px;
    background: white;
    font-size: ${fontSizeSmall};
    display: flex;
`;

export const BoardContentFooter = styledComponent.div`
    display: flex;
    align-items: center;
    flex: 1;
    color: inherit;
`;

export const BoardContent = styled.span`
    flex: 1;
`;
```

Need to investigate why this is blowing up - try to replicate locally.

```
ERROR in ./src/packages/deep-dive-card/src/ui/set-up-jsd-card/styled.js
Module build failed (from ./scripts/webpack/custom-babel-loader.js):
TypeError: value.includes is not a function
    at OldValue.check (/Users/mdougall/projects/jira-frontend/node_modules/autoprefixer/lib/old-value.js:20:15)
    at /Users/mdougall/projects/jira-frontend/node_modules/autoprefixer/lib/processor.js:437:22
    at /Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/container.js:190:18
    at /Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/container.js:131:17)
    at /Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/container.js:148:24
    at Root.each (/Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/container.js:131:17)
    at Root.walkDecls (/Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/container.js:188:19)
    at Processor.remove (/Users/mdougall/projects/jira-frontend/node_modules/autoprefixer/lib/processor.js:392:16)
    at plugin (/Users/mdougall/projects/jira-frontend/node_modules/autoprefixer/lib/autoprefixer.js:115:26)
    at LazyResult.run (/Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.sync (/Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/lazy-result.js:281:26)
    at LazyResult.stringify (/Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/lazy-result.js:305:10)
    at LazyResult.get (/Users/mdougall/projects/jira-frontend/node_modules/postcss/lib/lazy-result.js:350:19)
 @ ./src/packages/deep-dive-card/src/ui/set-up-jsd-card/main.js 11:0-192 31:42-57 41:38-44 57:39-46 64:38-61 71:197-218 78:38-48 85:38-57 101:120-135 108:38-56 115:38-50
 @ ./src/packages/deep-dive-card/src/ui/set-up-jsd-card/index.js
 @ ./src/packages/deep-dive-card/src/ui/main.js
 @ ./src/packages/deep-dive-card/src/ui/index.js
 @ ./src/packages/deep-dive-card/src/index.js
 @ ./src/packages/global-pages/home/src/ui/recent-projects/index.js
 @ ./src/packages/global-pages/home/src/ui/main.js
 @ ./src/packages/global-pages/home/src/ui/index.js
 @ ./src/packages/global-pages/home/src/index.js
 @ ./src/packages/spa-apps/jira-home/src/index.js
 @ ./src/packages/routes/src/ui/spa/jira-home/index.js
 @ ./src/packages/routes/src/ui/spa/index.js
 @ ./src/packages/routes/src/ui/main.js
 @ ./src/packages/routes/src/ui/index.js
 @ ./src/packages/routes/src/index.js
 @ ./src/entry/jira-spa.js
 @ multi ./src/entry/jira-spa
ℹ ｢wdm｣: Failed to compile.
```

**Comment by madou** [comment]
Update

When converting this it blew up:

```js
const gridSize = 8;

export const InnerWrapper = styled.span`
    flex: 6;
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    margin: 0 ${gridSize}px;
`;
```
